language: java

git:
  depth: 1
  quiet: true

before_install:
  - echo "Cloning malcompiler dependencies..."
  - git clone --quiet --no-checkout https://github.com/apache/maven-jlink-plugin.git
  - cd maven-jlink-plugin
  - git checkout --quiet -b tmp d474b2d0c664faee2500fb3cb869898aca281b79
  - cd ..
  - git clone --quiet --depth 1 https://github.com/meta-attack-language/javapoet.git
  - git clone --quiet --depth 1 https://github.com/meta-attack-language/svgSalamander.git
  - echo "Cloning malcompiler..."
  - git clone --quiet --depth 1 https://github.com/meta-attack-language/malcompiler.git

install:
  - echo "Installing malcompiler dependencies..."
  - cd maven-jlink-plugin
  - mvn install --quiet --batch-mode --define maven.test.skip=true
  - echo "Installing javapoet..."
  - cd ../javapoet
  - mvn install --quiet --batch-mode --define maven.test.skip=true
  - echo "Installing svgSalamander..."
  - cd ../svgSalamander/svg-core
  - mvn install --quiet --batch-mode --define maven.test.skip=true
  - echo "Installing malcompiler..."
  - cd ../../malcompiler
  - mvn install --quiet --batch-mode --define maven.test.skip=true
  - cd ..

before_script:
  - echo "Cleaning up cloned dependencies"
  - rm -rf maven-jlink-plugin
  - rm -rf javapoet
  - rm -rf svgSalamander
  - rm -rf malcompiler

script:
  - echo "Installing exampleLang..."
  - mvn clean install --batch-mode --activate-profiles test-only
