language: java
dist: bionic
jdk: openjdk11

git:
  quiet: true

before_install:
  - echo "Cloning malcompiler dependencies..."
  - git clone --quiet --depth 1 https://github.com/mal-lang/javapoet.git
  - echo "Cloning malcompiler..."
  - git clone --quiet --depth 1 https://github.com/mal-lang/malcompiler.git

install:
  - echo "Installing malcompiler dependencies..."
  - cd javapoet
  - mvn install --quiet --batch-mode --define maven.test.skip=true
  - echo "Installing malcompiler..."
  - cd ../malcompiler
  - mvn install --quiet --batch-mode --define maven.test.skip=true
  - cd ..

before_script:
  - echo "Cleaning up cloned dependencies"
  - rm -rf javapoet
  - rm -rf malcompiler

script:
  - echo "Installing exampleLang..."
  - mvn clean install --batch-mode --activate-profiles test-only
