name: Maven Build
on:
  pull_request:
    branches:
    - master
jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
        check-latest: true

    - name: Maven Build
      run: mvn -B clean test

    - name: Maven Build
      run: mvn -B clean package -PsecuriCAD

    - name: Set up malc
      run: ./tools/scripts/setup-malc.sh

    - name: malc Build
      run: cd target && malc -i ../src/main/resources/icons -l ../LICENSE -n ../NOTICE ../src/main/mal/exampleLang.mal
